name: Update Github README Stats

on:
  push:
    branches: [ main ] # Triggers the workflow on push to the main branch
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight
  workflow_dispatch: # Allows you to run it manually

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push the images back to your repo

    steps:
      - uses: actions/checkout@v4

      - name: Generate Top Languages Card
        uses: readme-tools/github-readme-stats-action@v1
        with:
          card: top-langs
          options: username=hongggweiii&layout=compact
          path: profile/top-langs.svg
          token: ${{ secrets.GH_PAT }}

      - name: Commit and Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update GitHub stats cards" || exit 0
          git push